---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-redmine
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: my-redmineapp
  template:
    metadata:
      labels:
        app: my-redmineapp
    spec:
      containers:
      - image: redmine:4.1.1
        name: redmine
        ports:
        - containerPort: 3000
        env:
          - name: REDMINE_DB_POSTGRES
            value: database
          - name: REDMINE_DB_USERNAME
            value: postgres_user
          - name: REDMINE_DB_DATABASE
            value: postgres_database		  
          - name: REDMINE_DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: postgres-secret
          - name: REDMINE_SECRET_KEY_BASE
            valueFrom:
              secretKeyRef:
                name: redmine-secret
